import type {Metadata} from "next";
import "./globals.css";
import Providers from "@/app/providors";
import ThemeToggle from "@/components/global/theme-toggle";
import AppBar from "@/components/global/app-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body>
    <Providers>
      <AppBar />
      {children}
    </Providers>
    </body>
    </html>
  );
}
